### ISSUE TITLE
Borrar tareas

### ISSUE THREAD

**Issue by duducito15** [duducito15/cursophp#3]
Como usuario Quiero un botón para borrar las tareas Para tener un listado mas limpio

**Comment by 2018jhona** [comment]
En Avance

**Comment by Pepito2024** [comment]
necesito mas informacion

**Comment by ADRIELVIRTO12** [comment]
CONFIRMADO

**Comment by LADISLAOCOSTILLO** [comment]
YA LO CERRE LAS RAMAS CON EL TRABAJO

**Comment by duducito15** [comment]
Codigo levantado, ya se relaizaron las observaciones y correcciones, Listo!!!!
